version: "3.0"
services:
  newman-script:
    container_name: newman-script
    network_mode: host
    build:
      context: .
      dockerfile: DockerfileMain
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - .:/app
