version: "3.0"
services:
  newman-script-test:
    container_name: newman-script-test
    network_mode: host
    build:
      context: ./
      dockerfile: DockerfileTest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    expose:
      - 4045
    volumes:
      - .:/app
